AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'spec/**/*'
    - 'bin/*'
    - 'Gemfile.lock'
    - 'ckb-sdk-ruby.gemspec'
    - 'lib/bech32.rb'

Bundler/OrderedGems:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  # If `true`, strings which span multiple lines using `\` for continuation must
  # use the same type of quotes on each line.
  ConsistentQuotesInMultiline: false

Metrics/AbcSize:
  Max: 100

Metrics/MethodLength:
  CountComments: false
  Max: 50

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 120
