---
sudo: false
dist: xenial
language: ruby
cache: bundler
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.1
env:
  - SKIP_RPC_TESTS=true BOB_PRIVATE_KEY="0xe79f3207ea4980b7fed79956d5934249ceac4751a4fae01a0f7c4a96884bc4e3"
before_install:
  - gem install bundler -v 2.0.1
  - sudo apt-get update
  - sudo apt-get install -y libsodium-dev
install:
  - cd ~ && git clone https://github.com/bitcoin-core/secp256k1.git && cd - && cd ~/secp256k1 && ./autogen.sh && ./configure --enable-module-recovery && make && sudo make install && cd -
  - bundle install
script:
  - bundle exec rake
